{"sections":[],"hierarchy":{"paths":[["doc:\/\/Adyen\/documentation\/Adyen","doc:\/\/Adyen\/documentation\/Adyen\/AppleWalletError"]]},"metadata":{"modules":[{"name":"Adyen"}],"title":"Error Implementations","role":"collectionGroup","roleHeading":"API Collection"},"topicSections":[{"identifiers":["doc:\/\/Adyen\/documentation\/Adyen\/AppleWalletError\/localizedDescription"],"generated":true,"title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/Adyen\/documentation\/Adyen\/AppleWalletError\/Error-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","variants":[{"paths":["\/documentation\/adyen\/applewalleterror\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://Adyen/documentation/Adyen/AppleWalletError":{"abstract":[{"type":"text","text":"An error that occurred during adding a pass to apple wallet."}],"role":"symbol","type":"topic","identifier":"doc:\/\/Adyen\/documentation\/Adyen\/AppleWalletError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AppleWalletError"}],"url":"\/documentation\/adyen\/applewalleterror","title":"AppleWalletError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AppleWalletError","kind":"identifier"}]},"doc://Adyen/documentation/Adyen":{"type":"topic","role":"collection","identifier":"doc:\/\/Adyen\/documentation\/Adyen","kind":"symbol","abstract":[],"title":"Adyen","url":"\/documentation\/adyen"},"doc://Adyen/documentation/Adyen/AppleWalletError/localizedDescription":{"abstract":[],"role":"symbol","identifier":"doc:\/\/Adyen\/documentation\/Adyen\/AppleWalletError\/localizedDescription","type":"topic","kind":"symbol","title":"localizedDescription","url":"\/documentation\/adyen\/applewalleterror\/localizeddescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}}}